### ISSUE TITLE
Multiple images uploaded not showing on item detail

### ISSUE THREAD

**Issue by songproducer** [inoks/dcf#22]
The second image I uploaded was quite large (1.4 Mb). Uploading smaller pictures solves this issue. Is there a size limit somewhere? Would be great to automatically scale too large images down.

**Comment by inoks** [comment]
There no any limits set for image size in that project.
You need to check your web server config for such limits. For example Nginx by defualt limit upload size to 1Mb at [`client_max_body_size`](https://nginx.ru/en/docs/http/ngx_http_core_module.html#client_max_body_size) param.
Let me know if you have some other questions.

**Comment by songproducer** [comment]
Thanks! I have another question will open another issue and close this one
